FROM scratch

ADD 4bea10bf16674c2ce4e713d01e78259b4fb9b3251b6ea7aa72a511afc7418fe1.tar.xz /
ADD 6ed13ab57c73d5829e9e02d325fc74846f40b99be22750cb1212a66a9d950e11.tar.xz /
ADD 862bef5091e9d5baad1dc1f0b6ea916a1d192f6748e367cfaae4f5aaeb9d410a.tar.xz /
ADD 8fa6e620268ab56d0718e4079052227eb3a5e887f1c429fb75a88ed5c04f6659.tar.xz /

ENV LANG=en_US.UTF-8
ENV TZ=:/etc/localtime
ENV PATH=/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
ENV LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime

WORKDIR /var/task

ENTRYPOINT ["/lambda-entrypoint.sh"]
